[package]
name = "todo"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33.3"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"

[dev-dependencies]
tempfile = "3.2.0"
